version: "3"
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: housing-portal-dev
        restart: unless-stopped
        # restart: "no"
        ports:
            - "80:80"
        environment:
            TZ: "Asia/Singapore"
            MODULE_NAME: "api.main"
            GUNICORN_CONF: "/app/gunicorn_conf.py"
        volumes:
            - "./logs:/app/logs"
