version: "3"

services:
    web:
        build:
            context: ./src/frontend/
            dockerfile: Dockerfile
        container_name: housing-portal-web
        restart: unless-stopped
        ports:
            - 80:80
            # - 443:443
        environment:
            TZ: "Asia/Singapore"
        depends_on:
            - api
    api:
        build:
            context: ./src/api/
            dockerfile: Dockerfile
        container_name: housing-portal-api
        restart: unless-stopped
        ports:
            - 8080:8080
        environment:
            TZ: "Asia/Singapore"
            PORT: "8080"
            MODULE_NAME: "api.main"
            LOG_LEVEL: "debug"
            PRE_START_PATH: "/app/api/prestart.sh"
            # openssl rand -hex 32
            JWT_SECRET_KEY_PROD: "None" # For Production
            JWT_SECRET_KEY_DEV: "None" # For Development
            # Gunicorn workers
            MAX_WORKERS: "1"
        volumes:
            - "./logs:/app/logs"
