version: "3"
services:
    backend:
        build:
            context: ./src/api/
            dockerfile: Dockerfile
        container_name: housing-portal-api
        restart: unless-stopped
        ports:
            - "8080:8080"
        environment:
            TZ: "Asia/Singapore"
            PORT: "8080"
            MODULE_NAME: "api.main"
            LOG_LEVEL: "debug"
            PRE_START_PATH: "/app/api/prestart.sh"
        # volumes:
        #     - "./logs:/app/logs"
    web:
        build:
            context: ./src/frontend/
            dockerfile: Dockerfile
        container_name: housing-portal-nginx
        restart: unless-stopped
        ports:
            - "80:80"
        environment:
            TZ: "Asia/Singapore"
