name: CI

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Run Dev Env Setup Script
              run: |
                  pwd
                  set -euo pipefail
                  export TERM=xterm-256color
                  ./dev_setup.sh
            - name: Run Unit Tests
              run: |
                  source venv/bin/activate
                  pytest --cov=src tests --cov-report=xml
            - name: Upload coverage report to Codecov
              uses: codecov/codecov-action@v1
              with:
                  # token: ${{ secrets.CODECOV_TOKEN }}
                  files: ./coverage.xml
                  # directory: ./coverage/reports/
                  flags: unittests
                  env_vars: OS,PYTHON
                  name: codecov-umbrella
                  # fail_ci_if_error: true
                  # path_to_write_report: ./coverage/codecov_resport.txt
                  verbose: true
